### ISSUE TITLE
Botón de envíos no funcional

### ISSUE THREAD

**Issue by Racsoth** [Corven-T59/JudgeProject#37]
Al entrar al listado de problemas de un contest [1] o a Mis Soluciones, el botón de enviar soluciones aparece en la barra pero no funciona. Solamente sirve desde Scoreboard [2].

[1] http://10.154.12.26/contests/6/problems?locale=es
[2] http://10.154.12.26/contests/6/scoreboard?locale=es

**Comment by HatsuMora** [comment]
Fixed on 30abc43
