### ISSUE TITLE
Recuperar archivos de problema al editar

### ISSUE THREAD

**Issue by Racsoth** [Corven-T59/JudgeProject#38]
Cuando se edita un problema, se deben subir de nuevo los archivos de descripción, in y out, pero no se pueden ver los que están en ese momento puestos. Ello implica que el usuario debe tener copia en disco de esos archivos o no puede editar el problema.

Sería MUY deseable que se pudiesen descargar los archivos que están en ese momento en el servidor para editarlos en disco y volverlos a subir.

**Comment by HatsuMora** [comment]
Fixed on  b408cf1
